# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "EnigmaYYY"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 30

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/ro-arxiv-daily.json'
json_gitpage_path: './docs/ro-arxiv-daily-web.json'
json_wechat_path: './docs/ro-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Embodied Question Answering":
        filters: ["Embodied Question Answering", "3D Environment Question Answering", "Interactive Question Answering"]
    "Visual Question Answering":
        filters: ["Visual Question Answering", "3D Visual Question Answering"]
    "Embodied Agent":
        filters: ["Embodied Agent", "LLM Agent", "Embodied Task Completion"]
    "Embodied AI": 
        filters: ["Embodied AI", "Embodied AI Survey", "Embodied Intelligence"]
    "Vision Language Action Model": 
        filters: ["Vision Language Action Model", "Vision Language Action"]
    "Vision Language Navigation Model":
        filters: ["Vision Language Navigation Model", "Vision Language Navigation", "Embodied Navigation"]
        
