# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "EnigmaYYY"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/ro-arxiv-daily.json'
json_gitpage_path: './docs/ro-arxiv-daily-web.json'
json_wechat_path: './docs/ro-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "EQA":
        filters: ["EQA","Embodied Question Answering"]
    "Embodied Agent":
        filters: ["Embodied Agent", "LLM Agent"]
    "VLA": 
        filters: ["VLA", "Vision-Language-Action Model", "Vision-Language-Action"]
    "Embodied AI": 
        filters: ["Embodied AI", "Embodied AI Survey"]
        
